# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Shoe.create(brand: "alpha", model: "kicker 5 mid", price: 250, detail1: "ALPHA technology provides 'zero gravity feel' to maintain energy return", detail2: "External heel counter combined with stability chassis creates the ultimate in stable support", detail3: "3D molded midfoot panel provides added structure", detail4: "Full rubber outsole for elevated traction & durability", pic_url: "https://svgshare.com/i/JYn.svg")
Shoe.create(brand: "alpha", model: "kicker 5 low", price: 200, detail1: "ALPHA technology provides 'zero gravity feel' to maintain energy return", detail2: "External heel counter combined with stability chassis creates the ultimate in stable support", detail3: "3D molded midfoot panel provides added structure", detail4: "Full rubber outsole for elevated traction & durability", pic_url: "https://svgshare.com/i/JYo.svg")
Shoe.create(brand: "alpha", model: "kicker 5 run", price: 150, detail1: "ALPHA technology provides 'zero gravity feel' to maintain energy return", detail2: "External heel counter combined with stability chassis creates the ultimate in stable support", detail3: "3D molded midfoot panel provides added structure", detail4: "Full rubber outsole for elevated traction & durability", pic_url: "https://svgshare.com/i/J_8.svg")
Shoe.create(brand: "alpha", model: "kicker 5 air", price: 190, detail1: "ALPHA technology provides 'zero gravity feel' to maintain energy return", detail2: "External heel counter combined with stability chassis creates the ultimate in stable support", detail3: "3D molded midfoot panel provides added structure", detail4: "Full rubber outsole for elevated traction & durability", pic_url: "https://svgshare.com/i/JZd.svg")
Shoe.create(brand: "alpha", model: "kicker 5 bounce", price: 150, detail1: "ALPHA technology provides 'zero gravity feel' to maintain energy return", detail2: "External heel counter combined with stability chassis creates the ultimate in stable support", detail3: "3D molded midfoot panel provides added structure", detail4: "Full rubber outsole for elevated traction & durability", pic_url: "https://svgshare.com/i/J_9.svg")
Shoe.create(brand: "alpha", model: "kicker 5 galaxy", price: 220, detail1: "ALPHA technology provides 'zero gravity feel' to maintain energy return", detail2: "External heel counter combined with stability chassis creates the ultimate in stable support", detail3: "3D molded midfoot panel provides added structure", detail4: "Full rubber outsole for elevated traction & durability", pic_url: "https://svgshare.com/i/JZM.svg")

